export const LIST_ITEM_TYPE = {
  HEADER: "HEADER",
  ITEM: "ITEM",
  FOOTER: "FOOTER",
  SECTION_END: "SECTION_END",
  BOTTOM_SPACER: "BOTTOM_SPACER",
  EMPTY_ITEM: "EMPTY_ITEM"
};

export const ITEM_TYPE_HEADER = "HEADER";
export const ITEM_TYPE_INSTANCE = "INSTANCE";